apps/fyle_expense/urls.py
"""
expense app URL Configuration
"""
from django.urls import path

from apps.fyle_expense.views import ExpenseGroupView, ExpenseView, InvoiceDetailsView, ExpenseDetailsView

urlpatterns = [
    path('', ExpenseGroupView.as_view(), name="expense_groups"),
    path('<int:group_id>/expenses/', ExpenseView.as_view(), name='expenses'),
    path('<int:group_id>/expenses/<int:expense_id>/details/', ExpenseDetailsView.as_view(),
         name='expenses_details'),
    path('<int:group_id>/invoice/', InvoiceDetailsView.as_view(), name='invoice')
]

apps/xero_workspace/urls.py
"""
xero_workspace app URL Configuration
"""

from django.urls import path, include

from apps.fyle_connect.views import FyleTokenView
from apps.xero_connect.views import XeroTokenView
from apps.xero_workspace.views import WorkspaceView, EmployeeMappingView, \
    CategoryMappingView, CategoryMappingBulkUploadView, \
    EmployeeMappingBulkUploadView, ScheduleView, ProjectMappingView, \
    ProjectMappingBulkUploadView

app_name = 'xero_workspace'
urlpatterns = [
    path('', WorkspaceView.as_view(), name="workspace"),
    path('<int:workspace_id>/mappings/category_mapping/', CategoryMappingView.as_view(),
         name="category_mapping"),
    path('<int:workspace_id>/mappings/category_mapping/upload/', CategoryMappingBulkUploadView.as_view(),
         name="category_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/employee_mapping/', EmployeeMappingView.as_view(),
         name="employee_mapping"),
    path('<int:workspace_id>/mappings/employee_mapping/upload/', EmployeeMappingBulkUploadView.as_view(),
         name="employee_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/project_mapping/', ProjectMappingView.as_view(),
         name="project_mapping"),
    path('<int:workspace_id>/mappings/project_mapping/upload/', ProjectMappingBulkUploadView.as_view(),
         name="project_mapping_bulk_upload"),
    path('<int:workspace_id>/settings/source/', include('apps.fyle_connect.urls')),
    path('<int:workspace_id>/settings/destination/', include('apps.xero_connect.urls')),
    path('<int:workspace_id>/settings/schedule/', ScheduleView.as_view(), name="schedule"),
    path('<int:workspace_id>/expense_groups/', include('apps.fyle_expense.urls')),
    path('<int:workspace_id>/tasks/', include('apps.task_log.urls')),

    # Path for getting the Fyle authorisation code
    path('connect/fyle/', FyleTokenView.as_view(), name="fyle_authorise"),

    # Path for getting the Xero authorization code
    path('connect/xero/', XeroTokenView.as_view(), name="xero_authorize")

]

fyle_xero_integration_web_app/urls.py
from decorator_include import decorator_include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.user.views import UserLoginView
from apps.xero_workspace.decorators import is_workspace_user
from fyle_xero_integration_web_app import settings

urlpatterns = [path('admin/', admin.site.urls),
               path('accounts/', include('allauth.urls')),
               path('', UserLoginView.as_view(), name='home'),
               path('workspace/',
                    decorator_include([login_required, is_workspace_user],
                                      ('apps.xero_workspace.urls', 'xero_workspace'))),
               path('workspace_jobs/', include('apps.xero_workspace.job_urls'))
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/fyle_expense/models.py
from itertools import groupby

from django.contrib.postgres.fields import JSONField
from django.db import models

from apps.xero_workspace.models import Workspace, InvoiceLineItem, Invoice
from apps.xero_workspace.utils import connect_to_fyle


class Expense(models.Model):
    """
    Expense
    """
    id = models.AutoField(primary_key=True)
    employee_email = models.EmailField(max_length=255, unique=False, help_text='Email id of the Fyle employee')
    category = models.CharField(max_length=255, null=True, blank=True, help_text='Fyle Expense Category')
    sub_category = models.CharField(max_length=255, null=True, blank=True, help_text='Fyle Expense Sub-Category')
    vendor = models.CharField(max_length=255, null=True, blank=True, help_text="Vendor")
    purpose = models.TextField(null=True, blank=True, help_text='Purpose')
    expense_id = models.CharField(max_length=255, unique=True, help_text="Expense ID")
    expense_number = models.CharField(max_length=255, help_text="Expense Number")
    amount = models.FloatField(help_text="Amount")
    settlement_id = models.CharField(max_length=255, help_text="Settlement ID")
    report_id = models.CharField(max_length=255, help_text="Report ID")
    project = models.CharField(max_length=255, null=True, blank=True, help_text="Project")
    expense_created_at = models.DateTimeField(help_text="Expense created at")
    spent_at = models.DateTimeField(help_text="Expense spent at")
    reimbursable = models.BooleanField(help_text="Expense reimbursable or not")
    state = models.CharField(max_length=255, help_text="Expense state")
    invoice_line_item = models.ForeignKey(InvoiceLineItem, null=True, blank=True,
                                          on_delete=models.PROTECT, help_text="FK to InvoiceLineItem")
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return self.expense_id

    class Meta:
        ordering = ["-created_at"]
        get_latest_by = "created_at"

    @staticmethod
    def fetch_paid_expenses(workspace_id, updated_at):
        """
        Fetch expenses from Fyle API filtered by state and updated_at
        """
        connection = connect_to_fyle(workspace_id)
        if updated_at is None:
            expenses = connection.Expenses.get(state='PAID')
        else:
            expenses = connection.Expenses.get(
                state='PAID',
                updated_at=f'gte:{updated_at.strftime("%Y-%m-%dT%H:%M:%S.%-SZ")}'
            )
        return expenses

    @staticmethod
    def create_expense_objects(expenses):
        """
        Bulk create expense objects
        """
        expense_objects = [Expense(
            employee_email=expense['employee_email'],
            category=expense['category_name'],
            sub_category=expense['sub_category'],
            vendor=expense['vendor'],
            purpose=expense['purpose'],
            expense_id=expense['id'],
            expense_number=expense['expense_number'],
            amount=expense['amount'],
            settlement_id=expense['settlement_id'],
            report_id=expense['report_id'],
            project=expense['project_name'],
            expense_created_at=expense['created_at'],
            spent_at=expense['spent_at'],
            reimbursable=expense['reimbursable'],
            state=expense['state']
        ) for expense in expenses['data']]

        expense_objects = Expense.objects.bulk_create(expense_objects)
        return expense_objects


class ExpenseGroup(models.Model):
    """
    Expense Group
    """
    id = models.AutoField(primary_key=True)
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE,
                                  help_text="To which workspace this expense group belongs to")
    expenses = models.ManyToManyField(Expense, help_text="Expenses under this Expense Group")
    invoice = models.ForeignKey(Invoice, null=True, blank=True,
                                on_delete=models.PROTECT, help_text="FK to Invoice")
    description = JSONField(default=dict, help_text="Description")
    status = models.CharField(max_length=10, help_text="Status")
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["-created_at"]
        get_latest_by = "created_at"

    @staticmethod
    def group_expense_by_report_id(expense_objects, workspace_id, connection):
        """
        Group expense by report_id
        """
        expense_groups = []
        reports = connection.Reports.get(state='PAID')
        for report_id, _expense_group in groupby(expense_objects, key=lambda x: x.report_id):
            report = [report for report in reports['data'] if report_id == report['id']].pop()
            report_data = {
                "report_id": report['id'],
                "employee_email": report['employee_email'],
                "approved_at": report['approved_at']
            }
            expense_groups.append(ExpenseGroup(
                workspace=Workspace.objects.get(id=workspace_id),
                description=report_data
            ))
        return expense_groups

    @staticmethod
    def create_expense_groups(expense_groups):
        expense_group_objects = ExpenseGroup.objects.bulk_create(expense_groups)
        through_model_objects = []
        for expense_group_object in expense_group_objects:
            report_id = expense_group_object.description['report_id']
            expenses = Expense.objects.filter(report_id=report_id)
            for expense in expenses:
                through_model_objects.append(ExpenseGroup.expenses.through(
                    expensegroup_id=expense_group_object.id,
                    expense_id=expense.id
                ))
        ExpenseGroup.expenses.through.objects.bulk_create(through_model_objects)
        return expense_group_objects

apps/fyle_expense/views.py
import ast

from dateutil.parser import parse
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.forms import model_to_dict
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.fyle_expense.models import ExpenseGroup, Expense
from apps.task_log.models import TaskLog
from apps.task_log.tasks import create_invoice_and_post_to_xero, \
    schedule_invoice_creation
from apps.task_log.tasks import fetch_expenses_and_create_groups
from apps.xero_workspace.models import CategoryMapping


class ExpenseGroupView(View):
    """
    Expense Group View
    """
    template_name = "expense/expense_group.html"

    def get(self, request, workspace_id):
        """
        Render expense group screen with necessary fields
        :param request
        :param workspace_id
        :return: render expense groups screen
        """
        context = {"expense_groups_tab": "active"}

        if request.GET.get('state') == 'complete':
            expense_groups = ExpenseGroup.objects.filter(
                workspace__id=workspace_id,
                status="Complete"
            )
            context["complete"] = "active"
        elif request.GET.get('state') == 'failed':
            expense_groups = ExpenseGroup.objects.filter(
                workspace__id=workspace_id,
                status="Failed"
            )
            context["failed"] = "active"
        else:
            expense_groups = ExpenseGroup.objects.filter(
                workspace__id=workspace_id
            )
            context["all"] = "active"

        for expense_group in expense_groups:
            expense_group.description["approved_at"] = parse(expense_group.description["approved_at"])

        page = request.GET.get('page', 1)
        paginator = Paginator(expense_groups, 10)
        try:
            expense_groups = paginator.page(page)
        except PageNotAnInteger:
            expense_groups = paginator.page(1)
        except EmptyPage:
            expense_groups = paginator.page(paginator.num_pages)

        context["expense_groups"] = expense_groups
        return render(request, self.template_name, context)

    def post(self, request, workspace_id):
        value = request.POST.get('submit')
        expense_group_ids = [ast.literal_eval(x) for x in request.POST.getlist('expense_group_ids')]
        if value == 'resync' and expense_group_ids:
            schedule_invoice_creation(workspace_id, expense_group_ids, request.user)
            messages.success(request, 'Resync started successfully. Expenses will be exported soon!')
        return HttpResponseRedirect(self.request.path_info)


class ExpenseView(View):
    """
    Expense View
    """
    template_name = "expense/expense.html"

    def get(self, request, workspace_id, group_id):
        """
        Render expenses screen with necessary fields
        :param request
        :param workspace_id
        :param group_id
        :return: render expenses screen
        """
        expense_group = ExpenseGroup.objects.get(id=group_id)
        report_id = expense_group.description["report_id"]
        expense_group_status = expense_group.status
        expenses = expense_group.expenses.all()

        page = request.GET.get('page', 1)
        paginator = Paginator(expenses, 10)
        try:
            expenses = paginator.page(page)
        except PageNotAnInteger:
            expenses = paginator.page(1)
        except EmptyPage:
            expenses = paginator.page(paginator.num_pages)

        context = {"expense_groups_tab": "active", "expenses": expenses,
                   "report_id": report_id, "expense_group_id": expense_group.id,
                   "status": expense_group_status}
        return render(request, self.template_name, context)


class ExpenseDetailsView(View):
    """
    Expense details view
    """

    @staticmethod
    def get(request, workspace_id, group_id, expense_id):
        """
        Return fields for expense details modal
        :param request
        :param workspace_id
        :param group_id
        :param expense_id
        :return: expense fields JSON
        """
        expense = Expense.objects.get(id=expense_id)
        expense_fields = model_to_dict(expense)
        expense_fields["category_code"] = CategoryMapping.objects.get(
            workspace__id=workspace_id, category=expense.category).account_code
        expense_fields["expense_created_at"] = expense.expense_created_at.strftime('%b. %d, %Y, %-I:%M %-p')
        expense_fields["spent_at"] = expense.spent_at.strftime('%b. %d, %Y, %-I:%M %-p')
        return JsonResponse(expense_fields)


class InvoiceDetailsView(View):
    """
    Invoice details view
    """

    @staticmethod
    def get(request, workspace_id, group_id):
        """
        Return fields for invoice details modal
        :param request
        :param workspace_id
        :param group_id
        :return: invoice fields JSON
        """
        invoice = ExpenseGroup.objects.get(id=group_id).invoice
        invoice_fields = model_to_dict(invoice)
        invoice_fields["date"] = invoice.date.strftime('%b. %d, %Y, %-I:%M %-p')
        invoice_fields["line_items"] = []
        for invoice_line_item in invoice.invoice_line_items.all():
            invoice_fields["line_items"].append(model_to_dict(invoice_line_item))
        return JsonResponse(invoice_fields)


class ExpenseGroupTriggerView(APIView):
    """
    Expense Group creation job trigger view
    """
    http_method_names = ['post']

    def post(self, request, workspace_id):
        task_log = TaskLog.objects.get(id=request.data.get('task_log_id'))

        fetch_expenses_and_create_groups(workspace_id, task_log, request.user)

        return Response(status=status.HTTP_200_OK)


class InvoiceTriggerView(APIView):
    """
    Invoice creation job trigger view
    """
    http_method_names = ['post']

    def post(self, request, workspace_id, group_id):
        task_log_id = request.data.get('task_log_id')

        expense_group = ExpenseGroup.objects.get(id=group_id)
        task_log = TaskLog.objects.get(id=task_log_id)

        create_invoice_and_post_to_xero(expense_group, task_log)

        return Response(status=status.HTTP_200_OK)

apps/fyle_expense/templates/expense/expense.html
{% extends "base.html" %}

{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/expense/expense.css' %}">
    <link rel="stylesheet" href="{% static 'css/xero_workspace/invoice.css' %}">
{% endblock %}

{% block title %}Expense Groups{% endblock %}

{% block back-button %}
    <a class="back-btn" href="{% url 'xero_workspace:expense_groups' workspace_id %}">
        <i class="material-icons">arrow_back</i>
    </a>
{% endblock %}

{% block sub-nav-heading %}Expenses{% endblock %}

{% block content %}
    <div class="content">
        <form action="" method="post">
            {% csrf_token %}
            <div class="d-flex content-header">
                <p class="employee-email">Report ID: {{report_id}}</p>
                {% if status == 'Complete' %}
                    <button class="view-invoice-modal ml-auto btn main-btn" type="button"
                            data-url="{% url 'xero_workspace:invoice' workspace_id expense_group_id %}">View Invoice
                {% else %}
                    <button class="view-invoice-modal ml-auto btn main-btn" type="button"
                            data-url="{% url 'xero_workspace:invoice' workspace_id expense_group_id %}"
                            disabled>View Invoice
                {% endif %}
                </button>
            </div>
            <div class="table-layout">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="table-head">
                            <tr class="colHeadings">
                                <th>Expense Number</th>
                                <th>Spend Date</th>
                                <th>Created on</th>
                                <th>Amount</th>
                                <th>Project</th>
                                <th>Purpose</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for expense in expenses %}
                                <tr class="expenses-table-row" data-url="{{expense.id}}/details/">
                                    <td>{{expense.expense_number}}</td>
                                    <td>{{expense.spent_at}}</td>
                                    <td>{{expense.expense_created_at}}</td>
                                    <td>{{expense.amount}}</td>
                                    <td>{{expense.project}}</td>
                                    {% if expense.purpose %}
                                        <td>{{expense.purpose}}</td>
                                    {% else %}
                                        <td>None</td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>

    <!-- Modal -->
    <div class="modal right fade" id="expenseModal" tabindex="-1" role="dialog"
         aria-labelledby="expenseModalTitle">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h5 class="modal-title" id="expenseModalTitle">Expense Details</h5>
                </div>
                <div class="modal-body expense-details">
                    <p id="employee-email" class="employee-email"></p>
                    <div class="table-responsive">
                        <table class="table expenses-table">
                            <tbody>
                                <tr>
                                    <td>ID</td>
                                    <td id="expense-id"></td>
                                </tr>
                                <tr>
                                    <td>Created Date</td>
                                    <td id="created-date"></td>
                                </tr>
                                <tr>
                                    <td>Spend Date</td>
                                    <td id="spent-date"></td>
                                </tr>
                                <tr>
                                    <td>Category</td>
                                    <td id="category"></td>
                                </tr>
                                <tr>
                                    <td>Category Code</td>
                                    <td id="category-code"></td>
                                </tr>
                                <tr>
                                    <td>Merchant</td>
                                    <td id="merchant"></td>
                                </tr>
                                <tr>
                                    <td>Purpose</td>
                                    <td id="purpose"></td>
                                </tr>
                                <tr>
                                    <td>Project</td>
                                    <td id="project"></td>
                                </tr>
                                <tr>
                                    <td>Reimbursable</td>
                                    <td id="reimbursable"></td>
                                </tr>
                                <tr>
                                    <td>State</td>
                                    <td id="state"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="nav-pagination">
        {% if expenses.has_other_pages %}
           <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if expenses.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ expenses.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
                    {% endif %}

                    {% if expenses.number|add:'-4' > 1 %}
                        <li class="page-item"><a class="page-link" href="?page={{ expenses.number|add:'-5' }}">&hellip;</a></li>
                    {% endif %}

                    {% for i in expenses.paginator.page_range %}
                        {% if expenses.number == i %}
                            <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
                        {% elif i > expenses.number|add:'-5' and i < expenses.number|add:'5' %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if expenses.paginator.num_pages > expenses.number|add:'4' %}
                        <li class="page-item"><a class="page-link" href="?page={{ expenses.number|add:'5' }}">&hellip;</a></li>
                    {% endif %}

                    {% if expenses.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ expenses.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
                    {% endif %}
                </ul>
           </nav>
        {% endif %}
    </div>

    {% include 'xero_workspace/invoice.html' %}

{% endblock %}

{% block include-script %}
    <script src="{% static 'js/expense/open_invoice_modal.js' %}"></script>
{% endblock %}

{% block script %}
    $("#select-all").click(function () {
        $(".expenseCheckbox").prop('checked', $(this).prop('checked'));
    });

    $(".expenses-table-row").click(function() {
        $.ajax({
            url: $(this).attr("data-url"),
            type: 'get',
            dataType: 'json',
            beforeSend: function() {
                $("#expenseModal").modal("show");
            },
            success: function(data) {
                $('#employee-email').html(`Email: ${data.employee_email}`);
                $("#expense-id").html(data.expense_id);
                $("#created-date").html(data.expense_created_at);
                $("#spent-date").html(data.spent_at);
                $("#category").html(data.category);
                $("#category-code").html(data.category_code || '-')
                $("#merchant").html(data.vendor || '-');
                $("#purpose").html(data.purpose || '-');
                $("#project").html(data.project || '-');
                $("#reimbursable").html(data.reimbursable);
                $("#state").html(data.state);
            }
        })
    });
{% endblock %}