apps/fyle_connect/urls.py
"""
fyle_connect app URL Configuration
"""
from django.urls import path

from apps.fyle_connect.views import FyleConnectView, FyleDisconnectView, SourceView

urlpatterns = [
    path('', SourceView.as_view(), name="source"),
    path('connect/', FyleConnectView.as_view(), name="fyle_connect"),
    path('disconnect/', FyleDisconnectView.as_view(), name="fyle_disconnect"),
]

apps/xero_workspace/urls.py
"""
xero_workspace app URL Configuration
"""

from django.urls import path, include

from apps.fyle_connect.views import FyleTokenView
from apps.xero_connect.views import XeroTokenView
from apps.xero_workspace.views import WorkspaceView, EmployeeMappingView, \
    CategoryMappingView, CategoryMappingBulkUploadView, \
    EmployeeMappingBulkUploadView, ScheduleView, ProjectMappingView, \
    ProjectMappingBulkUploadView

app_name = 'xero_workspace'
urlpatterns = [
    path('', WorkspaceView.as_view(), name="workspace"),
    path('<int:workspace_id>/mappings/category_mapping/', CategoryMappingView.as_view(),
         name="category_mapping"),
    path('<int:workspace_id>/mappings/category_mapping/upload/', CategoryMappingBulkUploadView.as_view(),
         name="category_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/employee_mapping/', EmployeeMappingView.as_view(),
         name="employee_mapping"),
    path('<int:workspace_id>/mappings/employee_mapping/upload/', EmployeeMappingBulkUploadView.as_view(),
         name="employee_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/project_mapping/', ProjectMappingView.as_view(),
         name="project_mapping"),
    path('<int:workspace_id>/mappings/project_mapping/upload/', ProjectMappingBulkUploadView.as_view(),
         name="project_mapping_bulk_upload"),
    path('<int:workspace_id>/settings/source/', include('apps.fyle_connect.urls')),
    path('<int:workspace_id>/settings/destination/', include('apps.xero_connect.urls')),
    path('<int:workspace_id>/settings/schedule/', ScheduleView.as_view(), name="schedule"),
    path('<int:workspace_id>/expense_groups/', include('apps.fyle_expense.urls')),
    path('<int:workspace_id>/tasks/', include('apps.task_log.urls')),

    # Path for getting the Fyle authorisation code
    path('connect/fyle/', FyleTokenView.as_view(), name="fyle_authorise"),

    # Path for getting the Xero authorization code
    path('connect/xero/', XeroTokenView.as_view(), name="xero_authorize")

]

fyle_xero_integration_web_app/urls.py
from decorator_include import decorator_include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.user.views import UserLoginView
from apps.xero_workspace.decorators import is_workspace_user
from fyle_xero_integration_web_app import settings

urlpatterns = [path('admin/', admin.site.urls),
               path('accounts/', include('allauth.urls')),
               path('', UserLoginView.as_view(), name='home'),
               path('workspace/',
                    decorator_include([login_required, is_workspace_user],
                                      ('apps.xero_workspace.urls', 'xero_workspace'))),
               path('workspace_jobs/', include('apps.xero_workspace.job_urls'))
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/fyle_connect/models.py
from django.db import models


class FyleAuth(models.Model):
    """
    Fyle (Source) credentials
    """
    id = models.AutoField(primary_key=True, )
    url = models.URLField(max_length=300, default='https://app.fyle.in',
                          help_text='Base URL of the fyle environment')  # default?
    client_id = models.CharField(max_length=256, help_text='Client Id')
    client_secret = models.CharField(max_length=256, help_text='Client Secret')
    refresh_token = models.CharField(max_length=512, help_text='Refresh Token')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)

apps/fyle_connect/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from apps.fyle_connect.models import FyleAuth
from apps.fyle_connect.utils import FyleOAuth2
from apps.xero_workspace.models import Workspace, FyleCredential
from fyle_xero_integration_web_app.settings import FYLE_BASE_URL


class SourceView(View):
    """
    Fyle (source) connect view
    """
    template_name = "fyle_connect/source.html"

    def get(self, request, workspace_id):
        connected = FyleCredential.objects.filter(workspace__id=workspace_id).exists()
        context = {"source": "active", "connected": connected,
                   "settings_tab": "active"}
        return render(request, self.template_name, context)


class FyleConnectView(View):
    """
    Fyle (source) connect view
    """

    @staticmethod
    def post(request, workspace_id):
        fyle_oauth = FyleOAuth2()
        return redirect(fyle_oauth.authorise(str(workspace_id)))


class FyleDisconnectView(View):
    """
    Fyle (source) disconnect view
    """

    @staticmethod
    def post(request, workspace_id):
        FyleAuth.objects.get(id=FyleCredential.objects.get(workspace__id=workspace_id).fyle_auth.id).delete()
        return HttpResponseRedirect(reverse('xero_workspace:source', args=[workspace_id]))


class FyleTokenView(View):
    """
    Exchange code for token and redirect to workspace URL using state
    """

    def get(self, request):
        code = request.GET.get('code')
        workspace_id = request.GET.get('state')
        if code is not None and workspace_id is not None:
            fyle_oauth = FyleOAuth2()
            tokens = fyle_oauth.get_tokens(code)
            access_token = tokens.get('access_token')
            refresh_token = tokens.get('refresh_token')
            if access_token is not None and refresh_token is not None:
                fyle_auth = FyleAuth.objects.create(url=FYLE_BASE_URL, refresh_token=refresh_token)
                FyleCredential.objects.create(fyle_auth=fyle_auth, workspace=Workspace.objects.get(id=workspace_id))
        return HttpResponseRedirect(reverse('xero_workspace:source', args=[workspace_id]))

apps/fyle_connect/templates/fyle_connect/source.html
{% extends "xero_workspace/settings.html" %}

{% load static %}

{% load socialaccount %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
{% endblock %}

{% block title %}Source{% endblock %}

{% block content %}
    <div class="login center-div">
        {% if connected %}
            <p>Connected to your Fyle account</p>
            <button class="btn btn-lg main-btn" type="button" data-toggle="modal" data-target="#FyleDisconnectModal">Disconnect</button>
        {% else %}
            <p>Connect to your Fyle account</p>
            <form action="{% url 'xero_workspace:fyle_connect' workspace_id %}" method="post">
            {% csrf_token %}
                <button class="btn btn-lg main-btn" type="submit">Connect</button>
            </form>

        {% endif %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="FyleDisconnectModal" tabindex="-1" role="dialog"
         aria-labelledby="FyleDisconnectModalTitle" aria-hidden="true"
         data-keyboard="false" data-backdrop="static">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="FyleDisconnectModalTitle">Warning!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="{% url 'xero_workspace:fyle_disconnect' workspace_id %}" method="post">
              {% csrf_token %}
              <div class="modal-body">
                  <p>Are you sure you want to disconnect your Fyle account from this workspace?</p>
              </div>
              <div class="modal-footer">
                <button class="btn btnInline cancelBtn" type="button" data-dismiss="modal">No</button>
                <button class="btn btnInline saveBtn" type="submit">Yes</button>
              </div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

apps/fyle_connect/templates/fyle_connect/source_connect.html
{% extends "base.html" %}

{% load static %}

{% load socialaccount %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/navtab.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <link rel="stylesheet" href="{% static 'css/connect.css' %}">
{% endblock %}

{% block title %}Source{% endblock %}

{% block navbar-header %}{{workspace_name}}{% endblock %}

{% block content %}
    {% include 'layouts/navtab.html' %}

    <div class="login center-div">
        {% if is_connected %}
            <p>Connected to your Fyle account</p>
            <button class="btn btn-lg main-btn" type="button" data-toggle="modal" data-target="#FyleDisconnectModal">Disconnect</button>
        {% else %}
            <p>Connect to your Fyle account</p>
            <form action="" method="post">
            {% csrf_token %}
                <button class="btn btn-lg main-btn" type="submit" name="type" value="connect">Connect</button>
            </form>

        {% endif %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="FyleDisconnectModal" tabindex="-1" role="dialog" aria-labelledby="FyleDisconnectModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="FyleDisconnectModalTitle">Warning!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form action="" method="post">
              {% csrf_token %}
              <div class="modal-body">
                  <p>Are you sure you want to disconnect your Fyle account from this workspace?</p>
              </div>
              <div class="modal-footer">
                <button class="btn btnInline cancelBtn" type="button" data-dismiss="modal">No</button>
                <button class="btn btnInline saveBtn" type="submit" name="type" value="disconnect">Yes</button>
              </div>
          </form>
        </div>
      </div>
    </div>
{% endblock %}