apps/fyle_connect/urls.py
"""
fyle_connect app URL Configuration
"""
from django.urls import path

from apps.fyle_connect.views import FyleConnectView, FyleDisconnectView, SourceView

urlpatterns = [
    path('', SourceView.as_view(), name="source"),
    path('connect/', FyleConnectView.as_view(), name="fyle_connect"),
    path('disconnect/', FyleDisconnectView.as_view(), name="fyle_disconnect"),
]

apps/xero_connect/urls.py
"""
xero_connect app URL Configuration
"""

from django.urls import path

from apps.xero_connect.views import DestinationView, XeroConnectView, XeroDisconnectView

urlpatterns = [
    path('', DestinationView.as_view(), name="destination"),
    path('connect/', XeroConnectView.as_view(), name="xero_connect"),
    path('disconnect/', XeroDisconnectView.as_view(), name="xero_disconnect"),
]

apps/xero_workspace/urls.py
"""
xero_workspace app URL Configuration
"""

from django.urls import path, include

from apps.fyle_connect.views import FyleTokenView
from apps.xero_connect.views import XeroTokenView
from apps.xero_workspace.views import WorkspaceView, EmployeeMappingView, \
    CategoryMappingView, CategoryMappingBulkUploadView, \
    EmployeeMappingBulkUploadView, ScheduleView, ProjectMappingView, \
    ProjectMappingBulkUploadView

app_name = 'xero_workspace'
urlpatterns = [
    path('', WorkspaceView.as_view(), name="workspace"),
    path('<int:workspace_id>/mappings/category_mapping/', CategoryMappingView.as_view(),
         name="category_mapping"),
    path('<int:workspace_id>/mappings/category_mapping/upload/', CategoryMappingBulkUploadView.as_view(),
         name="category_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/employee_mapping/', EmployeeMappingView.as_view(),
         name="employee_mapping"),
    path('<int:workspace_id>/mappings/employee_mapping/upload/', EmployeeMappingBulkUploadView.as_view(),
         name="employee_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/project_mapping/', ProjectMappingView.as_view(),
         name="project_mapping"),
    path('<int:workspace_id>/mappings/project_mapping/upload/', ProjectMappingBulkUploadView.as_view(),
         name="project_mapping_bulk_upload"),
    path('<int:workspace_id>/settings/source/', include('apps.fyle_connect.urls')),
    path('<int:workspace_id>/settings/destination/', include('apps.xero_connect.urls')),
    path('<int:workspace_id>/settings/schedule/', ScheduleView.as_view(), name="schedule"),
    path('<int:workspace_id>/expense_groups/', include('apps.fyle_expense.urls')),
    path('<int:workspace_id>/tasks/', include('apps.task_log.urls')),

    # Path for getting the Fyle authorisation code
    path('connect/fyle/', FyleTokenView.as_view(), name="fyle_authorise"),

    # Path for getting the Xero authorization code
    path('connect/xero/', XeroTokenView.as_view(), name="xero_authorize")

]

fyle_xero_integration_web_app/urls.py
from decorator_include import decorator_include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.user.views import UserLoginView
from apps.xero_workspace.decorators import is_workspace_user
from fyle_xero_integration_web_app import settings

urlpatterns = [path('admin/', admin.site.urls),
               path('accounts/', include('allauth.urls')),
               path('', UserLoginView.as_view(), name='home'),
               path('workspace/',
                    decorator_include([login_required, is_workspace_user],
                                      ('apps.xero_workspace.urls', 'xero_workspace'))),
               path('workspace_jobs/', include('apps.xero_workspace.job_urls'))
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/xero_workspace/models.py
from datetime import datetime

import pytz
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.fyle_connect.models import FyleAuth
from apps.user.models import UserProfile
from apps.xero_connect.models import XeroAuth


def default_for_json_field():
    return {"mappings": []}


class Workspace(models.Model):
    """
    Workspace for Fyle Xero integration
    """
    id = models.AutoField(primary_key=True, )
    name = models.CharField(max_length=20, help_text='Name of this workspace')
    user = models.ManyToManyField(UserProfile, help_text='Users belonging to this workspace')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return self.name


class EmployeeMapping(models.Model):
    """
    Mapping table for Fyle Employee to Xero Contact
    """
    id = models.AutoField(primary_key=True)
    employee_email = models.EmailField(max_length=255, help_text='Email id of the Fyle employee')
    contact_name = models.CharField(max_length=255, help_text='Name of the Xero contact')
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, help_text='Workspace this mapping belongs to')
    invalid = models.BooleanField(default=False, help_text='Indicates if this mapping is invalid')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["-created_at"]
        unique_together = ['employee_email', 'workspace']


class CategoryMapping(models.Model):
    """
    Mapping table for Fyle Category, Sub-category and Xero Account Code
    """
    id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=64, help_text='Fyle Expense Category')
    sub_category = models.CharField(max_length=64, null=True, default='Unspecified',
                                    help_text='Fyle Expense Sub-Category')
    account_code = models.CharField(max_length=32, null=True, blank=True, help_text='Xero Account code')
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, help_text='Workspace this mapping belongs to')
    invalid = models.BooleanField(default=False, help_text='Indicates if this mapping is invalid')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["-created_at"]
        unique_together = ['category', 'sub_category', 'workspace']


class ProjectMapping(models.Model):
    """
    Mapping table for Fyle Project, Xero Tracking Category and Tracking Category options
    """
    id = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=64, help_text='Fyle Project Name')
    tracking_category_name = models.CharField(max_length=64, help_text='Xero Tracking Category Name')
    tracking_category_option = models.CharField(max_length=64, help_text='Xero Tracking Category Option')
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, help_text='Workspace this mapping belongs to')
    invalid = models.BooleanField(default=False, help_text='Indicates if this mapping is invalid')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ["-created_at"]
        unique_together = ['project_name', 'workspace']


class XeroCredential(models.Model):
    """
    Xero credentials
    """
    id = models.AutoField(primary_key=True, help_text='id')
    xero_auth = models.OneToOneField(XeroAuth, on_delete=models.CASCADE,
                                     help_text='FK to Xero Auth')
    workspace = models.OneToOneField(Workspace, on_delete=models.CASCADE, help_text='Workspace')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)


class FyleCredential(models.Model):
    """
    Workspace Fyle Credentials  (Intermediate Table)
    """
    id = models.AutoField(primary_key=True, )
    fyle_auth = models.OneToOneField(FyleAuth, on_delete=models.CASCADE,
                                     help_text='FK to Fyle Auth')
    workspace = models.OneToOneField(Workspace, on_delete=models.CASCADE,
                                     help_text='FK to Workspace')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)


class WorkspaceSchedule(models.Model):
    """
    Schedule for Xero workspace
    """
    id = models.AutoField(primary_key=True, )
    workspace = models.OneToOneField(Workspace, on_delete=models.CASCADE,
                                     help_text='FK to Workspace')
    enabled = models.BooleanField(default=False, help_text="Schedule enabled")
    start_datetime = models.DateTimeField(null=True, help_text='Datetime for start of schedule')
    interval_hours = models.IntegerField(null=True, help_text='Interval in hours')
    fyle_job_id = models.CharField(unique=True, null=True, max_length=255, help_text='Fyle job ID')
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)


@receiver(post_save, sender=Workspace, dispatch_uid='workspace_create_signal')
def create_workspace(instance, created, **kwargs):
    if created:
        WorkspaceSchedule.objects.create(
            workspace=instance,
            start_datetime=datetime.now(tz=pytz.UTC),
            interval_hours=1
        )


class Invoice(models.Model):
    """
    Invoice model
    """
    id = models.AutoField(primary_key=True)
    invoice_number = models.CharField(max_length=64, help_text="Invoice number")
    invoice_id = models.CharField(max_length=64, null=True, blank=True, help_text="Invoice id")
    contact_name = models.CharField(max_length=64, help_text="Contact Name")
    date = models.DateTimeField(help_text="Invoice created date")
    due_date = models.DateTimeField(null=True, blank=True, help_text="Invoice due date")
    description = models.CharField(max_length=64, help_text="Description")
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)

    @staticmethod
    def delete_invoice(expense_group):
        """
        Delete invoice and it's line items
        """
        invoice_id = expense_group.invoice.id
        expense_group.invoice = None
        expense_group.save()
        for expense in expense_group.expenses.all():
            expense.invoice_line_item = None
            expense.save()

        Invoice.objects.filter(id=invoice_id).delete()

    @staticmethod
    def create_invoice(expense_group):
        """
        Create invoice from expense group
        :param expense_group
        :return: invoice id
        """
        description = expense_group.description
        invoice = Invoice.objects.create(
            invoice_number=description.get("report_id"),
            description=description.get("report_id"),
            contact_name=EmployeeMapping.objects.get(
                employee_email=description.get("employee_email")).contact_name,
            date=description.get("approved_at")
        )
        expense_group.invoice = invoice
        expense_group.save()
        return invoice.id


class InvoiceLineItem(models.Model):
    """
    Invoice line item model
    """
    id = models.AutoField(primary_key=True)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE,
                                related_name="invoice_line_items", help_text="FK to Invoice")
    account_code = models.CharField(max_length=32, help_text="Account Code")
    account_name = models.CharField(max_length=64, help_text="Account name")
    description = models.CharField(max_length=64, help_text="Description")
    amount = models.FloatField(help_text="Invoice line item amount")
    tracking_category_name = models.CharField(max_length=64, null=True, blank=True,
                                              help_text="Tracking Category Name")
    tracking_category_option = models.CharField(max_length=64, null=True, blank=True,
                                                help_text="Tracking Category Option")
    created_at = models.DateTimeField(auto_now_add=True, help_text='Created at')
    updated_at = models.DateTimeField(auto_now=True, help_text='Updated at')

    def __str__(self):
        return str(self.id)

    @staticmethod
    def create_invoice_line_item(invoice_id, expense_group):
        """
        Create Invoice line item from expenses and update ExpenseGroup
        and Expense model fields
        :param invoice_id
        :param expense_group
        """
        expenses = expense_group.expenses.all()
        for expense in expenses:
            invoice_line_item = InvoiceLineItem.objects.create(
                invoice=Invoice.objects.get(id=invoice_id),
                account_code=CategoryMapping.objects.get(
                    workspace=expense_group.workspace,
                    category=expense.category).account_code,
                account_name="",
                description=expense.report_id,
                amount=expense.amount
            )

apps/xero_workspace/forms.py
from django import forms
from tempus_dominus.widgets import DateTimePicker


class CategoryMappingForm(forms.Form):
    """
    Form for getting category mapping key and value
    """
    category = forms.CharField(max_length=64, label='Category*', help_text=None,
                               widget=forms.TextInput(attrs={'placeholder': ' ',
                                                             'autocomplete': 'off'}))
    sub_category = forms.CharField(max_length=64, label='Subcategory', help_text=None, required=False,
                                   widget=forms.TextInput(attrs={'placeholder': ' ',
                                                                 'autocomplete': 'off'}))
    account_code = forms.CharField(max_length=32, label='Account Code*', help_text=None,
                                   widget=forms.NumberInput(attrs={'placeholder': ' '}))
    bulk_upload_file = forms.FileField(label='', help_text=None,
                                       widget=forms.FileInput(attrs={'accept': '.xlsx'}))


class EmployeeMappingForm(forms.Form):
    """
    Form for getting employee mapping key and value
    """
    employee_email = forms.CharField(max_length=64, label='Employee Email*', help_text=None,
                                     widget=forms.TextInput(attrs={'placeholder': ' ',
                                                                   'autocomplete': 'off'}))
    contact_name = forms.CharField(max_length=64, label='Contact Name*', help_text=None,
                                   widget=forms.TextInput(attrs={'placeholder': ' ',
                                                                 'autocomplete': 'off'}))
    bulk_upload_file = forms.FileField(label='', help_text=None,
                                       widget=forms.FileInput(attrs={'accept': '.xlsx'}))


class ProjectMappingForm(forms.Form):
    """
    Form for getting project mapping key and value
    """
    project_name = forms.CharField(max_length=64, label='Project Name*', help_text=None,
                                   widget=forms.TextInput(attrs={'placeholder': ' ',
                                                                 'autocomplete': 'off'}))
    tracking_category_name = forms.CharField(max_length=64, label='Tracking Category Name*',
                                             help_text=None,
                                             widget=forms.TextInput(attrs={'placeholder': ' ',
                                                                           'autocomplete': 'off'}))
    tracking_category_option = forms.CharField(max_length=64, label='Tracking Category Option*',
                                               help_text=None,
                                               widget=forms.TextInput(attrs={'placeholder': ' ',
                                                                             'autocomplete': 'off'}))
    bulk_upload_file = forms.FileField(label='', help_text=None,
                                       widget=forms.FileInput(attrs={'accept': '.xlsx'}))


class ScheduleForm(forms.Form):
    """
    Form to get schedule data
    """

    start_datetime = forms.DateTimeField(widget=DateTimePicker(
        options={
            'useCurrent': True,
            'format': 'YYYY-MM-DD hh:mm a',
        },
        attrs={
            'icon_toggle': True
        }
    ))

    hours = forms.IntegerField(initial='3', widget=forms.NumberInput(attrs={
        'placeholder': 'in hours'
    }))

apps/xero_workspace/templates/xero_workspace/category_mapping.html
{% extends "xero_workspace/mappings.html" %}

{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/table.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
{% endblock %}

{% block title %}Category Mapping{% endblock %}

{% block content %}
    <div class="content">
        <div class="d-flex content-header">
            <h5 class="cardMainText">Category Mapping</h5>
            <button class="ml-auto btn main-btn" type="button" data-toggle="modal"
                    data-target="#categoryMappingModal">New Mapping
            </button>
            <button class="btn main-btn-outline ml-3" type="button" data-toggle="modal"
                    data-target="#bulkAddMappingModal">Bulk Add/Update
            </button>
            <button class="btn main-btn-outline delete-btn ml-3" type="submit" form="delete-form"
                    name="method" value="delete">Delete
            </button>
        </div>
        {% if mappings|length == 0 %}
            <div class="alert alert-light mx-auto warning" role="alert">
                <p>Looks like you don't have any Category Mappings</p>
            </div>
        {% else %}
            <div class="table-layout">
                <div class="table-responsive">
                    <table class="table">
                        <thead class="table-head">
                        <tr class="colHeadings">
                            <th style="width: 35%">category name (Fyle)</th>
                            <th style="width: 35%">Sub-category name (Fyle)</th>
                            <th class="actions">Account Code (Xero)</th>
                            <th>
                                <label class="checkbox-label">
                                    <input type="checkbox" id="select-all"/>
                                    <span class="checkmark"></span>
                                </label>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <form id="delete-form" action="" method="post">
                            {% csrf_token %}
                            {% for mapping in mappings %}
                            <tr onclick="openEditModal(this, {{mapping.id}})"
                                class="category-mapping-table{% if mapping.invalid %} highlight{% endif %}">
                                <td>{{mapping.category}}</td>
                                <td>{{mapping.sub_category}}</td>
                                <td class="actions">{{mapping.account_code}}</td>
                                <td class="checkbox-error">
                                    <label class="checkbox-label">
                                        <input type="checkbox" class="mappingsCheckbox" name="mapping_ids"
                                               value='"{{mapping.id}}"'/>
                                        <span id="checkmark" class="checkmark"></span>
                                    </label>
                                    {% if mapping.invalid %}
                                        <i class="material-icons error-icon"
                                           title="Please update this mapping">error</i>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </form>
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    </div>

    <div class="nav-pagination">
        {% if mappings.has_other_pages %}
           <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if mappings.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page={{ mappings.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
                    {% endif %}

                    {% if mappings.number|add:'-4' > 1 %}
                        <li class="page-item"><a class="page-link" href="?page={{ mappings.number|add:'-5' }}">&hellip;</a></li>
                    {% endif %}

                    {% for i in mappings.paginator.page_range %}
                        {% if mappings.number == i %}
                            <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
                        {% elif i > mappings.number|add:'-5' and i < mappings.number|add:'5' %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if mappings.paginator.num_pages > mappings.number|add:'4' %}
                        <li class="page-item"><a class="page-link" href="?page={{ mappings.number|add:'5' }}">&hellip;</a></li>
                    {% endif %}

                    {% if mappings.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ mappings.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
                    {% endif %}
                </ul>
           </nav>
        {% endif %}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="categoryMappingModal" tabindex="-1" role="dialog"
         aria-labelledby="categoryMappingModalTitle" aria-hidden="true"
         data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="categoryMappingModalTitle">Create New Mapping</h5>
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close" onclick="clearModalValues()">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="floating-label">
                            {{ form.category }}
                            <label class="input-label">{{ form.category.label }}</label>
                        </div>
                        <div class="floating-label">
                            {{ form.sub_category }}
                            <label class="input-label">{{ form.sub_category.label }}</label>
                        </div>
                        <div class="floating-label">
                            {{ form.account_code }}
                            <label class="input-label">{{ form.account_code.label }}</label>
                        </div>
                        <input type="hidden" id="mapping_id" name="mapping_id">
                    </div>
                    <div class="modal-footer">
                        <button id="cancel-btn" class="btn btnInline cancelBtn" type="button"
                                data-dismiss="modal" onclick="clearModalValues()">Cancel</button>
                        <button id="submit-btn" class="btn btnInline saveBtn" type="submit" name="method">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="bulkAddMappingModal" tabindex="-1" role="dialog"
         aria-labelledby="bulkAddMappingModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="bulkAddMappingModalTitle">Bulk Upload Mappings</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'xero_workspace:category_mapping_bulk_upload' workspace_id %}"
                      method="post" enctype="multipart/form-data">
                    <div class="modal-body">
                        {% csrf_token %}
                        {{ form.bulk_upload_file }}
                    </div>
                    <div class="modal-footer">
                        <button class="btn btnInline cancelBtn" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btnInline saveBtn" type="submit">Upload</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    $(document).ready(function() {
        $("#select-all").click(function() {
            $(".mappingsCheckbox").prop('checked', $(this).prop('checked'));
        });
    });

    $(".mappingsCheckbox").click(function(e) {
        if(e.target.type === 'checkbox') {
            e.stopPropagation();
        }
    });

    function openEditModal(table_row, mapping_id) {
        if (event.target.id !== 'checkmark') {
            const cells = table_row.getElementsByTagName('td');
            $('#id_category').val(cells[0].innerHTML);
            $('#id_sub_category').val(cells[1].innerHTML);
            $('#id_account_code').val(cells[2].innerHTML);
            $('#categoryMappingModalTitle').text('Edit Mapping');
            $('#submit-btn').text('Update');
            $('#submit-btn').val('update');
            $('#mapping_id').val(mapping_id.toString());
            $('#categoryMappingModal').modal('show');
        }
    }

    function clearModalValues() {
        setTimeout(function(){
            $('#categoryMappingModalTitle').text('Create New Mapping');
            $('#id_category').val('');
            $('#id_sub_category').val('');
            $('#id_account_code').val('');
            $('#submit-btn').text('Create');
            $('#submit-btn').removeAttr('name');
            $('#submit-btn').removeAttr('val');
            $('#mapping_id').removeAttr('val');
        }, 150);
    }

{% endblock %}

apps/xero_workspace/templates/xero_workspace/invoice.html
<div class="modal right fade" id="invoiceModal" tabindex="-1" role="dialog"
     aria-labelledby="invoiceModalTitle">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="invoiceModalTitle">Invoice Details</h5>
            </div>
            <div class="modal-body invoice-details">
                <div class="invoice-info">
                    <div class="invoice-id-date">
                        <p>
                            <span>Invoice Id:</span>
                            <span id="invoice-id"></span>
                        </p>
                        <p class="invoice-date">
                            <span>Date:</span>
                            <span id="invoice-date"></span>
                        </p>
                    </div>
                    <p>
                        <span>Invoice Number:</span>
                        <span id="invoice-number"></span>
                    </p>
                    <p>
                        <span>Contact Name:</span>
                        <span id="contact-name"></span>
                    </p>
                    <p>
                        <span>Description:</span>
                        <span id="description"></span>
                    </p>
                </div>
                <div class="table-layout">
                    <div class="table-responsive">
                        <table class="table invoice-details-table">
                            <thead class="table-head">
                                <tr class="colHeadings">
                                    <th>Account</th>
                                    <th>Amount</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

apps/xero_workspace/templates/xero_workspace/mappings.html
{% extends "base.html" %}

{% load static %}

{% block sub-nav-heading %}Mappings{% endblock %}

{% block sub-nav-tabs %}
    <li class="sub-nav-item">
        <a class="sub-nav-link {{ category_mapping }}"
           href="{% url 'xero_workspace:category_mapping' workspace_id %}">Category</a>
    </li>
    <li class="sub-nav-item">
        <a class="sub-nav-link {{ employee_mapping }}"
           href="{% url 'xero_workspace:employee_mapping' workspace_id %}">Employee</a>
    </li>
    <li class="sub-nav-item">
        <a class="sub-nav-link {{ project_mapping }}"
           href="{% url 'xero_workspace:project_mapping' workspace_id %}">Project</a>
    </li>
{% endblock %}

apps/xero_workspace/templates/xero_workspace/settings.html
{% extends "base.html" %}

{% load static %}

{% block sub-nav-heading %}Settings{% endblock %}

{% block sub-nav-tabs %}
    <li class="sub-nav-item">
        <a class="sub-nav-link {{ source }}"
           href="{% url 'xero_workspace:source' workspace_id %}">Source</a>
    </li>
    <li class="sub-nav-item">
        <a class="sub-nav-link {{ destination }}"
           href="{% url 'xero_workspace:destination' workspace_id %}">Destination</a>
    </li>
    <li class="sub-nav-item">
        <a class="sub-nav-link {{schedule}}"
           href="{% url 'xero_workspace:schedule' workspace_id %}">Schedule</a>
    </li>
{% endblock %}