apps/xero_workspace/urls.py
"""
xero_workspace app URL Configuration
"""

from django.urls import path, include

from apps.fyle_connect.views import FyleTokenView
from apps.xero_connect.views import XeroTokenView
from apps.xero_workspace.views import WorkspaceView, EmployeeMappingView, \
    CategoryMappingView, CategoryMappingBulkUploadView, \
    EmployeeMappingBulkUploadView, ScheduleView, ProjectMappingView, \
    ProjectMappingBulkUploadView

app_name = 'xero_workspace'
urlpatterns = [
    path('', WorkspaceView.as_view(), name="workspace"),
    path('<int:workspace_id>/mappings/category_mapping/', CategoryMappingView.as_view(),
         name="category_mapping"),
    path('<int:workspace_id>/mappings/category_mapping/upload/', CategoryMappingBulkUploadView.as_view(),
         name="category_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/employee_mapping/', EmployeeMappingView.as_view(),
         name="employee_mapping"),
    path('<int:workspace_id>/mappings/employee_mapping/upload/', EmployeeMappingBulkUploadView.as_view(),
         name="employee_mapping_bulk_upload"),
    path('<int:workspace_id>/mappings/project_mapping/', ProjectMappingView.as_view(),
         name="project_mapping"),
    path('<int:workspace_id>/mappings/project_mapping/upload/', ProjectMappingBulkUploadView.as_view(),
         name="project_mapping_bulk_upload"),
    path('<int:workspace_id>/settings/source/', include('apps.fyle_connect.urls')),
    path('<int:workspace_id>/settings/destination/', include('apps.xero_connect.urls')),
    path('<int:workspace_id>/settings/schedule/', ScheduleView.as_view(), name="schedule"),
    path('<int:workspace_id>/expense_groups/', include('apps.fyle_expense.urls')),
    path('<int:workspace_id>/tasks/', include('apps.task_log.urls')),

    # Path for getting the Fyle authorisation code
    path('connect/fyle/', FyleTokenView.as_view(), name="fyle_authorise"),

    # Path for getting the Xero authorization code
    path('connect/xero/', XeroTokenView.as_view(), name="xero_authorize")

]

fyle_xero_integration_web_app/urls.py
from decorator_include import decorator_include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.user.views import UserLoginView
from apps.xero_workspace.decorators import is_workspace_user
from fyle_xero_integration_web_app import settings

urlpatterns = [path('admin/', admin.site.urls),
               path('accounts/', include('allauth.urls')),
               path('', UserLoginView.as_view(), name='home'),
               path('workspace/',
                    decorator_include([login_required, is_workspace_user],
                                      ('apps.xero_workspace.urls', 'xero_workspace'))),
               path('workspace_jobs/', include('apps.xero_workspace.job_urls'))
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block link %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container-fluid">
    <div class="main-layout">
        <div class="msg">
            {% if messages %}
                {% for message in messages %}
                {% endfor %}
            {% endif %}
        </div>
        <ul class="nav nav-pills navTabsUl flex-column">
            <header class="sidenav-header">
                <div class="site-logo">
                    <img src="{% static 'fyle_logo_white_new.png' %}"
                         class="fyle-logo"/>
                </div>
            </header>
            <li class="nav-item">
                <a class="nav-link tabitem {{ tasks_tab }}"
                   href="{% url 'xero_workspace:tasks' workspace_id %}">Tasks</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tabitem {{ expense_groups_tab }}"
                   href="{% url 'xero_workspace:expense_groups' workspace_id %}">Expense Groups</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tabitem {{ mappings_tab }}"
                   href="{% url 'xero_workspace:category_mapping' workspace_id %}">Mappings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tabitem {{ settings_tab }}"
                   href="{% url 'xero_workspace:source' workspace_id %}">Settings</a>
            </li>
            <li class="nav-item mt-auto">
                <a class="nav-link tabitem"
                   href="{% url 'xero_workspace:workspace' %}">Switch Workspace</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tabitem"
                   onclick="document.getElementById('signout-form').submit()">Signout</a>
            </li>
        </ul>
        <div class="workspace-content">
            <nav class="navbar fixed-top navbar-light">
                <h1 class="navbar-brand">{{workspace_name}}</h1>
                <div class="msg">
                    {% include 'messages.html' %}
                </div>
                <div class="dropdown">
                    <button class="user-profile" type="button" id="profileBtn" data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false">
                        <div class="d-flex flex-row user-details">
                            <i class="material-icons user-icon">account_circle</i>
                            <div>
                                <strong class="user-name">{{username}}</strong>
                                <p class="org-name">{{org}}</p>
                            </div>
                            <i class="material-icons arrow-down">keyboard_arrow_down</i>
                        </div>
                    </button>
                    <div class="dropdown-menu profile-content" aria-labelledby="profileBtn">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4">
                                    <p data-letters={{username|first|capfirst}}></p>
                                </div>
                                <div class="col-md-8">
                                    <p class="profile-username">{{username}}</p>
                                    <p class="profile-organizationName">{{org}}</p>
                                </div>
                            </div>
                        </div>
                        <form id="signout-form" method="post" action="{% url 'account_logout' %}">
                            {% csrf_token %}
                            <button class="btn-block signoutBtn" type="submit">
                                <div class="d-flex signout-layout">
                                    <i class="material-icons icon">power_settings_new</i>
                                    <strong><p class="signout-text">Signout</p></strong>
                                </div>
                            </button>
                        </form>
                    </div>
                </div>
            </nav>
            <nav class="sub-navbar navbar fixed-top navbar-light d-flex flex-column">
                <div class="sub-navbar-heading">
                    {% block back-button %}{% endblock %}
                    <h1 class="navbar-brand">{% block sub-nav-heading %}{% endblock %}</h1>
                </div>
                <ul class="nav sub-nav-tabs d-flex flex-row" class="tabSection">
                    {% block sub-nav-tabs %}{% endblock %}
                </ul>
            </nav>
            <div class="tabitem-content">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
{% block include-script %}{% endblock %}
<script>{% block script %}{% endblock %}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
</body>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible message-overall" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}